name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

exclude-labels:
  - 'ignore-for-release'

template: |
  Here are the changes included in this version:

  $CHANGES

  ---
  *Released by **Gianmarco Raimondi***

categories:
  - title: 'Features & Modules'
    labels:
      - 'enhancement'
      - 'frontend'
      - 'backend'
      - 'database'

  - title: 'Bug Fixes'
    labels:
      - 'bug'

  - title: 'Performance Improvements'
    labels:
      - 'performance'

  - title: 'Documentation'
    labels:
      - 'documentation'

  - title: 'Refactoring & Code Quality'
    labels:
      - 'refactor'

  - title: 'Tests'
    labels:
      - 'test'

  - title: 'Build, CI/CD & Maintenance'
    labels:
      - 'build'
      - 'ci'
      - 'chore'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'