changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]

  categories:
    - title: "✨ Features & Modules"
      labels:
        - "enhancement"
        - "frontend"
        - "backend"
        - "database"

    - title: "Bug Fixes"
      labels:
        - "bug"

    - title: "Performance Improvements"
      labels:
        - "performance"

    - title: "Documentation"
      labels:
        - "documentation"

    - title: "Refactoring & Code Quality"
      labels:
        - "refactor"

    - title: "Tests"
      labels:
        - "test"

    - title: "Build, CI/CD & Maintenance"
      labels:
        - "build"
        - "ci"
        - "chore"

    - title: "Other Changes"
      labels:
        - "*"